---
driver:
  name: vagrant
provisioner:
  name: policyfile_zero
  require_chef_omnibus: true
  install_msi_url: http://packages.chef.io/stable/windows/2008r2/chef-client-12.14.89-1-x86.msi
  # vm's gateway is my virtualbox host running OSX squid, this saves me
  # re-downloading msi as long as squid runs on virtualbox host
  #http_proxy: http://10.0.2.2:3128
  log_level: info

platforms:
- name: ws7e
  os_type: windows
  driver_config:
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm
- name: mwrock/Windows2012R2
  os_type: windows
  driver_config:
    box: mwrock/Windows2012R2
    gui: false #headless
#    box_url: https://atlas.hashicorp.com/mwrock/boxes/Windows2012R2/versions/0.5.3/providers/virtualbox.box
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm
- name: mwrock/Windows2016
  os_type: windows
  driver_config:
    box: mwrock/Windows2016
    box_url: https://atlas.hashicorp.com/mwrock/boxes/Windows2016/versions/0.2.0/providers/virtualbox.box
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm

suites:
  - name: default
    run_list:
      - ["recipe[tm-php::default]"]
    attributes:
      