---
driver:
  name: vagrant
  driver_config:
    http_proxy: http://10.0.5.2:3128
    communicator: winrm
    vm_hostname: false
    gui: false

provisioner:
  name: policyfile_zero
  require_chef_omnibus: true
  install_msi_url: http://packages.chef.io/stable/windows/2008r2/chef-client-12.14.89-1-x86.msi
  # vm's gateway is my virtualbox host running OSX squid, this saves me
  # re-downloading msi as long as squid runs on virtualbox host
  log_level: info

platforms:
- name: ws7e1
  os_type: windows
  driver_config:
    box: ws7e1
  transport:
    name: winrm

- name: mwrock/Windows2012R2
  os_type: windows
  driver_config:
    network:
      - ['private_network', {ip: '192.168.33.34'}]
    box: mwrock/Windows2012R2
  transport:
    name: winrm

- name: mwrock/Windows2016
  os_type: windows
  driver_config:
    box: mwrock/Windows2016
    box_url: https://atlas.hashicorp.com/mwrock/boxes/Windows2016/versions/0.2.0/providers/virtualbox.box
  transport:
    name: winrm

- name: win10x64-enterprise
  os_type: windows
  driver_config:
    box: win10x64-enterprise
  transport:
    name: winrm

- name: win2008r2-standard
  os_type: windows
  driver_config:
    box: win2008r2-standard
  transport:
    name: winrm

- name: win2012r2-datacenter
  os_type: windows
  driver_config:
    box: win2012r2-datacenter
  transport:
    name: winrm

- name: win2012r2-standard
  os_type: windows
  driver_config:
    box: win2012r2-standard
  transport:
    name: winrm

- name: win7x64-enterprise
  os_type: windows
  driver_config:
    box: win7x64-enterprise
  transport:
    name: winrm

- name: win7x86-enterprise
  os_type: windows
  driver_config:
    box: win7x86-enterprise
  transport:
    name: winrm

- name: win81x64-enterprise
  os_type: windows
  driver_config:
    box: win81x64-enterprise
  transport:
    name: winrm

- name: win81x86-enterprise
  os_type: windows
  driver_config:
    box: win81x86-enterprise
  transport:
    name: winrm

suites:
  - name: default
    run_list:
      - ["recipe[tm-php::default]"]
