---
driver:
  name: vagrant
provisioner:
  name: policyfile_zero
  require_chef_omnibus: true
  install_msi_url: http://packages.chef.io/stable/windows/2012r2/chef-client-12.14.77-1-x86.msi
  # vm's gateway is my virtualbox host running OSX squid, this saves me
  # re-downloading msi as long as squid runs on virtualbox host
  http_proxy: http://10.0.2.2:3128

platforms:
- name: ws7e
  os_type: windows
  driver_config:
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm

suites:
- name: default
